- name: Remove datanode dir
  when: hadoop_reformat_namenode
  ansible.builtin.file:
    path: "{{ hadoop_hdfs_site['dfs.datanode.data.dir'] | default(hadoop_hdfs_site_defaults['dfs.datanode.data.dir']) }}"
    state: absent
  tags: hadoop, configureHadoopDataNode

- name: Create datanode dir
  ansible.builtin.file:
    path: "{{ hadoop_hdfs_site['dfs.datanode.data.dir'] | default(hadoop_hdfs_site_defaults['dfs.datanode.data.dir']) }}"
    state: directory
    owner: hdfs
    group: hadoop
    mode: "0755"
  tags: hadoop, configureHadoopDataNode
