- name: Create group hadoop
  ansible.builtin.group:
    name: hadoop
    gid: 33500
  tags: hadoop, configureHadoop

- name: Create user hadoop
  ansible.builtin.user:
    name: hadoop
    group: hadoop
    uid: 33511
  tags: hadoop, configureHadoop

- name: Create user and group hdfs
  ansible.builtin.user:
    name: hdfs
    group: hadoop
    uid: 33510
  tags: hadoop, configureHadoop

- name: Create user and group yarn
  ansible.builtin.user:
    name: yarn
    group: hadoop
    uid: 33520
  tags: hadoop, configureHadoop

- name: Create user and group mapred
  ansible.builtin.user:
    name: mapred
    group: hadoop
    uid: 33530
  tags: hadoop, configureHadoop
