- name: Set hadoop package name from URL
  when: hadoop_distro_local_pkg == None
  ansible.builtin.set_fact:
    hadoop_distro_pkg_name={{ hadoop_distro_url.split('/')[-1] }}

- name: Set hadoop package name from local package
  when: hadoop_distro_local_pkg != None
  ansible.builtin.set_fact:
    hadoop_distro_pkg_namer={{ hadoop_distro_local_pkg.split('/')[-1] }}

- name: Download hadoop distro
  when: hadoop_distro_local_pkg == None
  ansible.builtin.get_url:
    url: "{{ hadoop_distro_url }}"
    dest: "{{ hadoop_target_dir }}/{{ hadoop_distro_pkg_name }}"
    mode: "0555"
  tags: hadoop, installHadoop

- name: Copy local hadoop package to remote system
  when: hadoop_jre_local_pkg != None
  ansible.builtin.copy:
    src: "{{ hadoop_distro_local_pkg }}"
    dest: "{{ hadoop_target_dir }}/{{ hadoop_distro_pkg_name }}"
    mode: "0555"

- name: Unpack hadoop distro
  ansible.builtin.unarchive:
    src: "{{ hadoop_target_dir }}/{{ hadoop_distro_pkg_name }}"
    dest: "{{ hadoop_target_dir }}"
    list_files: true
    remote_src: true
  register: archive_contents
  tags: hadoop, installHadoop

- name: Create link to current hadoop distro
  ansible.builtin.file:
    path: "{{ hadoop_distro_home }}"
    src: "{{ archive_contents.files[0] }}"
    state: link
  tags: hadoop, installHadoop
