- name: format first namenode
  when: hadoop_reformat_namenode and inventory_hostname == groups['hadoop_namenodes'][0]
  become: true
  become_user: hdfs
  tags: hadoop, configureHadoopNameNode
  block:
  - name: stop NameNode
    ansible.builtin.shell: "{{ hadoop_distro_home }}/bin/hdfs --daemon stop namenode"

  - name: remove NameNode dir
    ansible.builtin.file:
        path: "{{ hadoop_hdfs_site['dfs.namenode.name.dir'] | default(hadoop_hdfs_site_defaults['dfs.namenode.name.dir']) }}"
        state: absent

  - name: format first NameNode
    ansible.builtin.shell: "{{ hadoop_distro_home }}/bin/hdfs namenode -format {{ hadoop_cluster_name }} -force -non-interactive"
