# - name: Stop service {{ hadoop_service_name }}
#  become: true
#  when: stop_service is not defined or stop_service
#  ignore_errors: true
#  ansible.builtin.shell: "sudo {{ hadoop_distro_home }}/bin/{{ hadoop_service_binary }} \
#                          --daemon stop {{ hadoop_service_name }}"

# - name: Start service {{ hadoop_service_name }}
#  become: true
#  when: start_service is not defined or start_service
#  ignore_errors: true
#  ansible.builtin.shell: "nohup sudo {{ hadoop_distro_home }}/bin/{{ hadoop_service_binary }} \
#                          --daemon start {{ hadoop_service_name }} && \
#                          {{ hadoop_distro_home }}/bin/{{ hadoop_service_binary }} \
#                          --daemon status {{ hadoop_service_name }}"
#  register: result
#  retries: 3
#  until: result.rc == 0
